version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ikoro
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - ikoro-network

  mysql:
    image: mysql:latest
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ikoro_db
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - ikoro-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8001:80
    networks:
      - ikoro-network

networks:
  ikoro-network:
    driver: bridge
